feat(snap): add go-based hooks for Kong user and TLS certificate
canonical/edgex-go pull request #29
Opened 2021-04-28 12:47 UTC by siggiskulason

1. Enable Kong user configuration using a snap configure hook:

Test this by doing the following:

First set up the user:

$ openssl ecparam -genkey -name prime256v1 -noout -out private.pem

$ openssl ec -in private.pem -pubout -out public.pem

$ sudo snap set edgexfoundry env.security-proxy.user=user01,USER_ID,ES256

$ sudo snap set edgexfoundry "env.security-proxy.public-key=$(cat public.pem)"

Then generate the JWT token, using the user ID and private key

It's possible to generate the token using a bash script on a different computer, or just using
the edgexfoundry.secrets-config tool. To use secrets-config, do:

$ edgexfoundry.secrets-config proxy jwt --algorithm ES256 --private_key private.pem --id USER_ID --expiration=1h

Copy the token. You can optionally validate it on https://jwt.io, where you can paste the token
and public key.

Using the JWT token from step 3, execute an EdgeX command:

curl -k -X GET https://localhost:8443/coredata/api/v1/ping? -H "Authorization: Bearer $TOKEN"

Expected result: "pong"

2. Set the TLS certificate

Start by generating a TLS certificate. One way to do so is to use the edgeca snap:

sudo snap install edgeca
edgeca gencsr --cn localhost --csr localhost.csr --key localhost.csrkey
edgeca gencert -o localhost.cert -i localhost.csr -k localhost.privatekey

Then install the certificate:

sudo snap set edgexfoundry "env.security-proxy.tls-certificate=$(cat localhost.cert)"
sudo snap set edgexfoundry "env.security-proxy.tls-private-key=$(cat localhost.privatekey)"

You can then connect, specifying the CA root cert used by edgeca:

curl -v --cacert /var/snap/edgeca/current/CA.pem -X GET https://localhost:8443/coredata/api/v1/ping

Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?

## Issue Number:

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## New Imports

- [ ] Yes
- [ ] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-04-29 21:44 UTC, tonyespy requested changes
This looks really good. I tested everything except the TLS flow w/SNI as I didn't have an easy way to set a hostname in my test environment. Let's discuss if this is worth it or not...

One of the things I noticed in your test instructions (which were great btw) was that you quote the actual config keys. In general you really only ever need to quote the value of a config value you're setting which contains whitespace and/or special characters which trip up the shell. Also when you included commands to clear values, you typically did this:

`$ sudo snap set edgexfoundry "foo="
`
whereas I usually use:

`$ sudo snap set edgexfoundry foo=""
`
...which is how I did most of my testing. When I reviewed your code I did notice that you check for empty strings, and you're not checking that the config value is unset, so I think we're OK.

One change I think you should make is to remove the log statement which writes the TLS private key to the log. At minimum this should be a Debug() call.

The only other comment is that most of the logging in configure.go and install.go use a log statement prefix (e.g. "edgexfoundry:configure" or "edgexfoundry:install"). I know this is more of a pita to do from the utils functions. I will probably change this when I modularize the code so that instead of calling hooks.InitLog(), it's probably closer to hooks.Init() and add a prefix parameter. Let's discuss tomorrow whether it's worth changing now, or waiting till the code gets re-factored.

2021-04-29 21:44 UTC, tonyespy commented on hooks/utils.go
> +
nit: general go style is to use less whitespace, especially blank lines in related lines of code...

2021-04-29 21:44 UTC, tonyespy commented on hooks/utils.go
> +
nit: same

2021-04-29 21:44 UTC, tonyespy commented on hooks/utils.go
> +	return
do you need a return if both path and err are always initialized?

2021-04-29 21:44 UTC, tonyespy commented on hooks/utils.go
> +	return
needed?

2021-04-29 21:44 UTC, tonyespy commented on hooks/utils.go
> +
whitespace...

2021-04-29 21:44 UTC, tonyespy commented on hooks/utils.go
> +			if k == "user" {
nit: this would be cleaner as a switch statement...

2021-04-30 09:41 UTC, siggiskulason commented on hooks/utils.go
> +	return
Yes, it's a naked return, which is required if the result parameters have names specified in the function declaration.
 
See https://golang.org/ref/spec#Return_statements :"The expression list may be empty if the function's result type specifies names for its result parameters. The result parameters act as ordinary local variables and the function may assign values to them as necessary. The "return" statement returns the values of these variables."

If I omit that return statement then I get an error: "/utils.go:302:1: missing return at end of function".

However, I personally have mixed feelings about the naked return pattern and would agree with https://dave.cheney.net/practical-go/presentations/gophercon-israel.html#_avoid_naked_returns in that "Naked returns are inconsistent; they make it look like the function or method returns no values, when infact it does, as they were declared in the function signature." 

So if you think this looks confusing then I'm happy to rewrite those functions to not use named result parameters and use a standard named return instead.

2021-04-30 09:42 UTC, siggiskulason commented on hooks/utils.go
> +	return
See comment above

2021-04-30 10:01 UTC, siggiskulason commented
> One change I think you should make is to remove the log statement which writes the TLS private key to the log. At minimum this should be a Debug() call.
Not sure I log that? which statement was that?

2021-04-30 10:04 UTC, siggiskulason commented
> One of the things I noticed in your test instructions (which were great btw) was that you quote the actual config keys. In general you really only ever need to quote the value of a config value you're setting which contains whitespace and/or special characters which trip up the shell. Also when you included commands to clear values, you typically did this:

Thank you! - and I've updated the test instructions accordingly.

2021-04-30 10:11 UTC, siggiskulason commented
Thank you for the review. I've force-pushed an update with
- whitespace removed
- case statement used in HandleEdgeXConfig

2021-04-30 13:06 UTC, tonyespy commented
I forgot one other issue... documentation. Can update the snap/README.md to describe the new options?

2021-04-30 16:26 UTC, siggiskulason commented
> I forgot one other issue... documentation. Can update the snap/README.md to describe the new options?

I've updated the README - ready for re-review.

2021-04-30 17:34 UTC, tonyespy requested changes
A couple of minor changes requested in your new README instructions, but otherwise looks good. Thanks for the changes!

2021-04-30 17:34 UTC, tonyespy commented on snap/README.md
> +The secrets-config command also supports using OAuth2. Do enable that you need to do the following:
I would add some disclaimer about that fact the EdgeX's usage of OAuth means tokens can only be created on the system running EdgeX (i.e. running the secrets-config command), and also that the generated tokens have infinite TTL.

2021-04-30 17:34 UTC, tonyespy commented on snap/README.md
> +Set KongAuth.Name to "oauth2" in the security-proxy-setup configuration.toml file
How would you change this value using the snap? While its true that we do copy all the service-specific configuration.toml files to $SNAP_DATA/config, most of the services are enabled by default, on install these services will read their configuration and provision their config into Consul before anyone has a chance to edit the config files. This is why we added the rich config hook, so these type of overrides can happen via the service wrapper sourcing service-specific environment files. So, this should instead suggest using snap set edgexfoundry env.security-proxy.authtype.name="oauth2", and then maybe mention that if this change can't be made after install.

2021-05-01 11:46 UTC, siggiskulason commented on snap/README.md
> +Set KongAuth.Name to "oauth2" in the security-proxy-setup configuration.toml file
Good that you raised that point. There are a few issues which came up once I looked into this

1.  As far as I can see, security-proxy-setup is different from the other security services in that it doesn't use AuthType.Name, but KongAuth.Name. Setting env.security-proxy.authtype.name="oauth2" doesn't therefore do anything. I changed const.go from

```
	// [AuthType]
	"authtype.name": "AUTHTYPE_NAME",
```
to

```
	// [KongAuth]
	"kongauth.name": "KONGAUTH_NAME",
```

Also, there are a number of reasons that this can't be done after install:

```
sudo snap set edgexfoundry env.security-proxy.kongauth.name=oauth2
sudo snap restart edgexfoundry.security-proxy-setup
```
- The Init() method in service.go in security-proxy-setup first checks if a certificate has been set up for Kong - if so, then none of the initialization is performed. As the default EdgeX TLS certificate was set up in the install hook then nothing is initialized. It can therefore really only run once. We can see this debug message in the journal:

```
msg="skipping as the initialization has been done successfully"
```
I tried deleting the current certificate first:

```
curl -XDELETE http://localhost:8001/certificates/localhost
```

But that isn't enough. As you said, we should therefore mention that this change can't be made after install. As such, it can only be done before the snap starts up for the first time - so only in a gadget snap I suppose? 

3. Also, as far as I can see - the security-proxy-setup configuration.toml file contents are not provisioned to Consul. security-proxy-setup seems to load the toml file each time. So we could in fact change the KongAuth value in $SNAP_DATA/config, but that wouldn't work - not because the value has been provisioned into Consul, but because Kong has already been initialized and can't be initialized again.

2021-05-01 12:22 UTC, siggiskulason commented on snap/README.md
> +The secrets-config command also supports using OAuth2. Do enable that you need to do the following:
Done, see coment below ->

2021-05-03 15:25 UTC, tonyespy requested changes
Changes look good, although I would make two minor changes:

- drop the bit about building a custom snap for oauth
- update the key name (i.e. `authtype.name` --> `kongauth.name`)

2021-05-03 15:44 UTC, siggiskulason commented
Excellent, Thank you,

>     * drop the bit about building a custom snap for oauth
> 
>     * update the key name (i.e. `authtype.name` --> `kongauth.name`)

- I dropped "or a custom version of the snap would need to be built, with `KongAuth.Name` set to "oauth2" in the security-proxy-setup configuration.toml file."

- Not quite sure what you are referring to with  * update the key name (i.e. `authtype.name` --> `kongauth.name`) " ?

2021-05-03 15:58 UTC, tonyespy approved these changes
LGTM

2021-05-03 15:59 UTC, merged