fix(snap): add ToC to snap/README.md
canonical/edgex-go pull request #33
Opened 2021-05-26 23:03 UTC by tonyespy

This changes adds a manually generated ToC to the snap/README file. It also changes some of the heading capitalization to ensure style consistency.

2021-05-27 20:50 UTC, tonyespy commented
@siggiskulason I've updated all the links and everything seems to be working OK now, so ready to review.

2021-06-01 15:57 UTC, siggiskulason requested changes
Looks good - just one link that needs fixing - see inline comment

2021-06-01 15:57 UTC, siggiskulason commented on snap/README.md
> +          + [OAuth 2.0](#oath-2.0)
This link doesn't work with the period in the version number - it needs to be "#oauth-20" (not #oauth-2.0)

2021-06-01 16:10 UTC, siggiskulason approved these changes
LGTM

2021-06-01 16:10 UTC, merged